spring:
  application:
    name: ks-zuul


server:
  port: 8765
zuul:
  prefix: /api #拦截所有api开头的请求
  routes:
    user-center:
      path: /uc/**
      serviceId: ks-uc

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/